language: node_js
cache:
  directories:
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: '08I4IaHS6pjRuE6DaXyobCuLmKXFtHzCICSXhgf3u219L7fzhlP2P0bPqgfvE85g3pdim4TMUDTJtbZH1onpYtnpTlxwP1MWmQOHugWAGZ899pG+LGzb2xCftCwR0Cae/xd0tOVAtvC6/h2COjduRzPEcv/imge+IWgz+uxfAGyvQ/ydVCWkKkyJ6ukm6OEgz5MatHihbnavJ3JXfyYnWC6RJtFbzlmtCa6M6w/1xwjNQjynXyToYmIzADrF5/y3tY6griIXz+wScXRDhUg1LRDr1Ry9kqQQikmRD2HTycn66/lD/pY1xczrYBbrj5CcOXs3jUiB941zV1DHLG80YgCsMbFCzvJTdCMRcSla1VF4QJJu6pWZSlqFCqCvR282Ku+JSbtBYIcPP9/Qj291M+Jj8XRAKIn2gJPP5RKLsYbij5AT4quHoAFMMqw4kCR1Xp7sUZo6o01AhnhngtmgUPYTJfJatxFCHOKc/9kvyjMtTXGDTUyvbls33BqU49U4lhSu+DyTewv7Nnc6BT4Pbhqv19NplP1QMYqpMhgkaqUSlQqpup0J/Tj5yi6P6Z/dFKvSth6UBlPSg8l4XwEvEuEojcQ49pAPxBT/oyk+DKT3v9+Sjobn5D9ffagsfGspzprUcCUyEiA24Ig6RhVeVMV/VQJwTm7AXWvrgwU/B08='
  app: songs-io
  target-branch: travis-deploy
  commit_message: Deploy release ${TRAVIS_TAG}
  on:
    branch: main
